<a href="https://colab.research.google.com/github/nano-rayhan/Machine-Learning-with-Phitron/blob/main/phtorch_training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [40]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [41]:
df.shape

(569, 33)

In [42]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [43]:
df.head()

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

# Train test split

In [44]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=.2)

# Scaling

In [45]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Label Encoding

In [46]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

# Numpy array to pytorch tensors

In [47]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

# Defining the model

In [48]:
class MySimpleNN():
  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    loss = - (y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1-y_pred)).mean()
    return loss

In [49]:
learning_rate = 0.1
epochs = 50

#Training Pipeline

In [50]:
model = MySimpleNN(X_train_tensor)

for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  print(f'Epoch: {epoch + 1} , loss: {loss.item()}')

Epoch: 1 , loss: 3.258357232207704
Epoch: 2 , loss: 3.1022614227625076
Epoch: 3 , loss: 2.94461848572692
Epoch: 4 , loss: 2.7816114055712764
Epoch: 5 , loss: 2.6078492154282578
Epoch: 6 , loss: 2.4337664910552923
Epoch: 7 , loss: 2.259810786692208
Epoch: 8 , loss: 2.08942185973842
Epoch: 9 , loss: 1.9220464069466163
Epoch: 10 , loss: 1.7593752352034107
Epoch: 11 , loss: 1.6010517226299774
Epoch: 12 , loss: 1.456296889379429
Epoch: 13 , loss: 1.3268790450616965
Epoch: 14 , loss: 1.2141891418593473
Epoch: 15 , loss: 1.1189926304902484
Epoch: 16 , loss: 1.0399513213537543
Epoch: 17 , loss: 0.9760285564176225
Epoch: 18 , loss: 0.9266829059076127
Epoch: 19 , loss: 0.8892087449854107
Epoch: 20 , loss: 0.86078066440087
Epoch: 21 , loss: 0.8388923398051007
Epoch: 22 , loss: 0.8215875227573031
Epoch: 23 , loss: 0.8074833284305138
Epoch: 24 , loss: 0.795663845798599
Epoch: 25 , loss: 0.7855398093318483
Epoch: 26 , loss: 0.7767304186213988
Epoch: 27 , loss: 0.7689815278861435
Epoch: 28 , loss: 0.7621146698481932
Epoch: 29 , loss: 0.7559971461759587
Epoch: 30 , loss: 0.7505250398046984
Epoch: 31 , loss: 0.745613662453295
Epoch: 32 , loss: 0.7411921069596947
Epoch: 33 , loss: 0.7372000076231455
Epoch: 34 , loss: 0.7335854758076986
Epoch: 35 , loss: 0.7303036678135549
Epoch: 36 , loss: 0.7273157072269635
Epoch: 37 , loss: 0.7245878221189277
Epoch: 38 , loss: 0.7220906268836201
Epoch: 39 , loss: 0.7197985121729618
Epoch: 40 , loss: 0.7176891221679607
Epoch: 41 , loss: 0.7157429056499047
Epoch: 42 , loss: 0.7139427306675916
Epoch: 43 , loss: 0.7122735542792953
Epoch: 44 , loss: 0.7107221398918729
Epoch: 45 , loss: 0.7092768155437329
Epoch: 46 , loss: 0.7079272672326196
Epoch: 47 , loss: 0.7066643621097063
Epoch: 48 , loss: 0.7054799970444644
Epoch: 49 , loss: 0.7043669686972024
Epoch: 50 , loss: 0.7033188618075333

# Evaluation

In [53]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > .9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6842105388641357